[project]
name = "my-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material>=9.6.14",
    "pymdown-extensions>=10.7",
    "pillow>=10.2.0",
    "cairosvg>=2.7.1",
]
