name: Deploy MkDocs Site
on:
  push:
    branches:
      - main  # Set this to your default branch
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Set up cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install uv
          uv pip install -r requirements.txt || pip install -r requirements.txt || echo "No requirements.txt found, continuing..."
      
      - name: Install additional dependencies
        run: |
          pip install fontawesome_markdown
          pip install mkdocs-glightbox
          pip install mkdocs-material-extensions
      
      - name: Deploy
        run: |
          mkdocs gh-deploy --force
